# -*- mode: ruby -*-
# vi: set ft=ruby :

# Originally from https://github.com/deviantony/docker-elk
DOCKER_COMPOSE_REPO = "https://github.com/deviantony/docker-elk"
DOCKER_COMPOSE_DIR = "/home/vagrant/#{DOCKER_COMPOSE_REPO.split("/")[-1]}"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ELK_vagrant"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 9300, host: 9300

  config.vm.provision "shell", inline: <<-SHELL
    sudo touch /var/lib/cloud/instance/locale-check.skip
    sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list'
    sudo apt-cache policy docker-engine
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y docker-engine python-pip git
    sudo pip install docker-compose
    sudo usermod -aG docker vagrant
    sudo -u vagrant pip install docker-compose
    sudo -u vagrant git clone #{DOCKER_COMPOSE_REPO}
    cd #{DOCKER_COMPOSE_DIR}
    sudo docker-compose -f docker-compose.yml up -d
    echo "su - vagrant -c 'docker-compose -f #{DOCKER_COMPOSE_DIR}/docker-compose.yml up -d' \nexit 0" > /etc/rc.local
  SHELL

end
